name: 'pre-commit with uv'
description: 'Run pre-commit hooks using uv for fast Python environment management'
author: 'Jakub3628800'

branding:
  icon: 'check-circle'
  color: 'purple'

inputs:
  command:
    description: 'Command to run: run (isolated), run-venv (with project deps), or autoupdate'
    required: false
    default: 'run'
  extra_args:
    description: 'Arguments to pass to pre-commit (e.g., --all-files, hook-id)'
    required: false
    default: '--all-files'

runs:
  using: 'composite'
  steps:
    - name: Cache pre-commit environments
      uses: actions/cache@v4
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-${{ runner.os }}-${{ hashFiles('**/.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-${{ runner.os }}-

    - name: Run pre-commit (isolated mode)
      if: inputs.command == 'run'
      shell: bash
      run: uv tool run pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}

    - name: Run pre-commit (with project environment)
      if: inputs.command == 'run-venv'
      shell: bash
      run: |
        uv sync
        uv run pre-commit run --show-diff-on-failure --color=always ${{ inputs.extra_args }}

    - name: Run pre-commit autoupdate
      if: inputs.command == 'autoupdate'
      shell: bash
      run: uv tool run pre-commit autoupdate
